### ISSUE TITLE
Crashes on Android 4.4.4 running on intel processor

### ISSUE THREAD

**Issue by hj91** [MPieter/Notification-Analyser#11]
I have a custom build of android 4.4.4 running on my intel laptop. I downloaded Notification Analyser from F-droid market and it got installed successfully but crashes on lauching main activity.

**Comment by hj91** [comment]
Recompiled source code and generated apk, and it runs well even on intel powered system.

**Comment by MPieter** [comment]
Great to hear!

**Comment by hj91** [comment]
Now trying to add all notification logs that can be shared in form of text file.
